import type { Metadata } from "next";
import MainNav from "@/app/(site)/MainNav";
import Footer from "@/app/(site)/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-screen flex flex-col ">
      <header>
        <MainNav />
      </header>
      <main className="grow">{children}</main>
      <Footer />
    </div>
  );
}
